app:
  trello:
    secretFileDirection: "./.secret/.trello.json"
    boardId: "5e8d6e60c3a2647221556d6a"
    listDoneNamePrefix: "DONE"
    listInReviewName: "IN REVIEW"
  slack:
    secretFileDirection: "./.secret/.slack.json"
    channelId: "C011FT91QLS"
    username: "Trelloの進捗発表くん"
